# Major Course Output
**STINTSY Section S21**

Presented by: **Learning Models**
- Chan, Sidney Sy
- Hsu, Aldrin Gamad
- Siongco, Raine Margaux Aceret
- Villas, Gabriel

Task: **Predicting a student's alcohol consumption level**

Features: school, sex, age, address, fam_size, Pstatus, Medu, Fedu, Mjob, Fjob, reason, guardian,
traveltime, studytime, failures,
schoolsup, famsup, paid, activities, nursery, higher, internet, romantic,
freetime, goout, health, absences, G3


Label: alcohol_consumption (Average of Dalc and Walc)

In [210]:
# Imports
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import torch.optim as optim
import torch.nn as nn
import numpy as np
import torch
import csv
import math
import pandas as pd

In [211]:
# To allow us to scroll through all the columns of our dataframes
pd.set_option('display.max_columns', None)

In [212]:
# Importing datasets using csv files
student_math = pd.read_csv('student-mat.csv', sep=';')
student_port = pd.read_csv('student-por.csv', sep=';')

In [213]:
student_math.head(10)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian,traveltime,studytime,failures,schoolsup,famsup,paid,activities,nursery,higher,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,course,mother,2,2,0,yes,no,no,no,yes,yes,no,no,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,course,father,1,2,0,no,yes,no,no,no,yes,yes,no,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,other,mother,1,2,3,yes,no,yes,no,yes,yes,yes,no,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,home,mother,1,3,0,no,yes,yes,yes,yes,yes,yes,yes,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,home,father,1,2,0,no,yes,yes,no,yes,yes,no,no,4,3,2,1,2,5,4,6,10,10
5,GP,M,16,U,LE3,T,4,3,services,other,reputation,mother,1,2,0,no,yes,yes,yes,yes,yes,yes,no,5,4,2,1,2,5,10,15,15,15
6,GP,M,16,U,LE3,T,2,2,other,other,home,mother,1,2,0,no,no,no,no,yes,yes,yes,no,4,4,4,1,1,3,0,12,12,11
7,GP,F,17,U,GT3,A,4,4,other,teacher,home,mother,2,2,0,yes,yes,no,no,yes,yes,no,no,4,1,4,1,1,1,6,6,5,6
8,GP,M,15,U,LE3,A,3,2,services,other,home,mother,1,2,0,no,yes,yes,no,yes,yes,yes,no,4,2,2,1,1,1,0,16,18,19
9,GP,M,15,U,GT3,T,3,4,other,other,home,mother,1,2,0,no,yes,yes,yes,yes,yes,yes,no,5,5,1,1,1,5,0,14,15,15

In [214]:
student_port.head(10)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian,traveltime,studytime,failures,schoolsup,famsup,paid,activities,nursery,higher,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,course,mother,2,2,0,yes,no,no,no,yes,yes,no,no,4,3,4,1,1,3,4,0,11,11
1,GP,F,17,U,GT3,T,1,1,at_home,other,course,father,1,2,0,no,yes,no,no,no,yes,yes,no,5,3,3,1,1,3,2,9,11,11
2,GP,F,15,U,LE3,T,1,1,at_home,other,other,mother,1,2,0,yes,no,no,no,yes,yes,yes,no,4,3,2,2,3,3,6,12,13,12
3,GP,F,15,U,GT3,T,4,2,health,services,home,mother,1,3,0,no,yes,no,yes,yes,yes,yes,yes,3,2,2,1,1,5,0,14,14,14
4,GP,F,16,U,GT3,T,3,3,other,other,home,father,1,2,0,no,yes,no,no,yes,yes,no,no,4,3,2,1,2,5,0,11,13,13
5,GP,M,16,U,LE3,T,4,3,services,other,reputation,mother,1,2,0,no,yes,no,yes,yes,yes,yes,no,5,4,2,1,2,5,6,12,12,13
6,GP,M,16,U,LE3,T,2,2,other,other,home,mother,1,2,0,no,no,no,no,yes,yes,yes,no,4,4,4,1,1,3,0,13,12,13
7,GP,F,17,U,GT3,A,4,4,other,teacher,home,mother,2,2,0,yes,yes,no,no,yes,yes,no,no,4,1,4,1,1,1,2,10,13,13
8,GP,M,15,U,LE3,A,3,2,services,other,home,mother,1,2,0,no,yes,no,no,yes,yes,yes,no,4,2,2,1,1,1,0,15,16,17
9,GP,M,15,U,GT3,T,3,4,other,other,home,mother,1,2,0,no,yes,no,yes,yes,yes,yes,no,5,5,1,1,1,5,0,12,12,13

In [215]:
# To check both datasets for zero values
print("Math Dataset Zeros")
print((student_math == 0).sum())

print("\nPortuguese Dataset Zeros")
print((student_port == 0).sum())

Math Dataset Zeros
school          0
sex             0
age             0
address         0
famsize         0
Pstatus         0
Medu            3
Fedu            2
Mjob            0
Fjob            0
reason          0
guardian        0
traveltime      0
studytime       0
failures      312
schoolsup       0
famsup          0
paid            0
activities      0
nursery         0
higher          0
internet        0
romantic        0
famrel          0
freetime        0
goout           0
Dalc            0
Walc            0
health          0
absences      115
G1              0
G2             13
G3             38
dtype: int64

Portuguese Dataset Zeros
school          0
sex             0
age             0
address         0
famsize         0
Pstatus         0
Medu            6
Fedu            7
Mjob            0
Fjob            0
reason          0
guardian        0
traveltime      0
studytime       0
failures      549
schoolsup       0
famsup          0
paid            0
activities      0
nursery         0
higher          0
internet        0
romantic        0
famrel          0
freetime        0
goout           0
Dalc            0
Walc            0
health          0
absences      244
G1              1
G2              7
G3             15
dtype: int64

In [216]:
# To check both datasets for missing values 
print("Math Dataset Missing Values")
print(student_math.isnull().sum())

print("\nPortuguese Dataset Missing Values")
print(student_port.isnull().sum())

Math Dataset Missing Values
school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
G1            0
G2            0
G3            0
dtype: int64

Portuguese Dataset Missing Values
school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
G1            0
G2            0
G3            0
dtype: int64

In [217]:
print("Math rows:", len(student_math))
print("Portuguese rows:", len(student_port))

Math rows: 395
Portuguese rows: 649

In [218]:
# Rename failures, absences, and G3 and remove G1 and G2 for both datasets
math_df = student_math.drop(columns=['G1', 'G2']).rename(columns={
    'G3': 'math_grade',
    'failures': 'math_failures',
    'absences': 'math_absences'
})

port_df = student_port.drop(columns=['G1', 'G2']).rename(columns={
    'G3': 'port_grade',
    'failures': 'port_failures',
    'absences': 'port_absences'
})

In [219]:
# Create combined_df by merging math_df and port_df on the stable columns
stable_cols = ['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu', 'Mjob', 'Fjob', 'reason', 'guardian',
               'traveltime', 'studytime', 'romantic', 'freetime', 'goout', 'Dalc', 'Walc', 'health',
               'schoolsup', 'famsup', 'paid', 'activities', 'nursery', 'higher', 'internet', 'famrel']

combined_df = pd.merge(math_df, port_df, on=stable_cols, how='outer', suffixes=('_math', '_port'))
print("Combined rows:", len(combined_df))

Combined rows: 843

In [220]:
combined_df.head(10)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian,traveltime,studytime,math_failures,schoolsup,famsup,paid,activities,nursery,higher,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,math_absences,math_grade,port_failures,port_absences,port_grade
0,GP,F,15,R,GT3,T,1,1,at_home,other,home,mother,2,4,1.0,yes,yes,yes,yes,yes,yes,yes,no,3,1,2,1,1,1,2.0,10.0,0.0,4.0,13.0
1,GP,F,15,R,GT3,T,1,1,other,other,course,mother,3,1,NaN,no,no,no,yes,yes,yes,yes,yes,5,5,5,1,1,1,NaN,NaN,1.0,2.0,9.0
2,GP,F,15,R,GT3,T,1,1,other,other,reputation,mother,1,2,2.0,yes,yes,no,no,no,yes,yes,yes,3,3,4,2,4,5,2.0,5.0,0.0,2.0,11.0
3,GP,F,15,R,GT3,T,2,2,at_home,other,reputation,mother,1,1,NaN,yes,yes,no,yes,yes,yes,no,no,4,3,1,1,1,2,NaN,NaN,0.0,8.0,12.0
4,GP,F,15,R,GT3,T,2,2,at_home,other,reputation,mother,1,1,0.0,yes,yes,yes,yes,yes,yes,no,no,4,3,1,1,1,2,8.0,13.0,NaN,NaN,NaN
5,GP,F,15,R,GT3,T,2,4,services,health,course,mother,1,3,NaN,yes,yes,no,yes,yes,yes,yes,no,4,3,2,1,1,5,NaN,NaN,0.0,2.0,10.0
6,GP,F,15,R,GT3,T,2,4,services,health,course,mother,1,3,0.0,yes,yes,yes,yes,yes,yes,yes,no,4,3,2,1,1,5,2.0,8.0,NaN,NaN,NaN
7,GP,F,15,R,GT3,T,3,3,services,services,reputation,other,2,3,2.0,no,yes,yes,yes,yes,yes,yes,yes,4,2,1,2,3,3,8.0,10.0,0.0,2.0,13.0
8,GP,F,15,R,GT3,T,3,4,services,health,course,mother,1,3,NaN,yes,yes,no,yes,yes,yes,yes,no,4,3,2,1,1,5,NaN,NaN,0.0,2.0,12.0
9,GP,F,15,R,GT3,T,3,4,services,health,course,mother,1,3,0.0,yes,yes,yes,yes,yes,yes,yes,no,4,3,2,1,1,5,2.0,11.0,NaN,NaN,NaN

In [221]:
# Rearrange combined_df to make it more intuitive to read and work with
cols = ['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu', 'Mjob', 'Fjob', 'reason', 'guardian', 
        'traveltime', 'studytime', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery', 'higher', 'internet', 
        'romantic', 'famrel', 'freetime', 'goout', 'Dalc', 'Walc', 'health', 
        'math_failures', 'port_failures',
        'math_absences', 'port_absences',
        'math_grade', 'port_grade']

combined_df = combined_df[cols]

In [223]:
# View rearranged combined_df
combined_df.head(10)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian,traveltime,studytime,schoolsup,famsup,paid,activities,nursery,higher,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,math_failures,port_failures,math_absences,port_absences,math_grade,port_grade
0,GP,F,15,R,GT3,T,1,1,at_home,other,home,mother,2,4,yes,yes,yes,yes,yes,yes,yes,no,3,1,2,1,1,1,1.0,0.0,2.0,4.0,10.0,13.0
1,GP,F,15,R,GT3,T,1,1,other,other,course,mother,3,1,no,no,no,yes,yes,yes,yes,yes,5,5,5,1,1,1,NaN,1.0,NaN,2.0,NaN,9.0
2,GP,F,15,R,GT3,T,1,1,other,other,reputation,mother,1,2,yes,yes,no,no,no,yes,yes,yes,3,3,4,2,4,5,2.0,0.0,2.0,2.0,5.0,11.0
3,GP,F,15,R,GT3,T,2,2,at_home,other,reputation,mother,1,1,yes,yes,no,yes,yes,yes,no,no,4,3,1,1,1,2,NaN,0.0,NaN,8.0,NaN,12.0
4,GP,F,15,R,GT3,T,2,2,at_home,other,reputation,mother,1,1,yes,yes,yes,yes,yes,yes,no,no,4,3,1,1,1,2,0.0,NaN,8.0,NaN,13.0,NaN
5,GP,F,15,R,GT3,T,2,4,services,health,course,mother,1,3,yes,yes,no,yes,yes,yes,yes,no,4,3,2,1,1,5,NaN,0.0,NaN,2.0,NaN,10.0
6,GP,F,15,R,GT3,T,2,4,services,health,course,mother,1,3,yes,yes,yes,yes,yes,yes,yes,no,4,3,2,1,1,5,0.0,NaN,2.0,NaN,8.0,NaN
7,GP,F,15,R,GT3,T,3,3,services,services,reputation,other,2,3,no,yes,yes,yes,yes,yes,yes,yes,4,2,1,2,3,3,2.0,0.0,8.0,2.0,10.0,13.0
8,GP,F,15,R,GT3,T,3,4,services,health,course,mother,1,3,yes,yes,no,yes,yes,yes,yes,no,4,3,2,1,1,5,NaN,0.0,NaN,2.0,NaN,12.0
9,GP,F,15,R,GT3,T,3,4,services,health,course,mother,1,3,yes,yes,yes,yes,yes,yes,yes,no,4,3,2,1,1,5,0.0,NaN,2.0,NaN,11.0,NaN