# Major Course Output
**STINTSY Section S21**

Presented by: **Learning Models**
- Chan, Sidney Sy
- Hsu, Aldrin Gamad
- Siongco, Raine Margaux Aceret
- Villas, Gabriel

Task: **Predicting a student's alcohol consumption level**

Features: school, sex, age, address, fam_size, Pstatus, Medu, Fedu, Mjob, Fjob, reason, guardian,
traveltime, studytime, failures,
schoolsup, famsup, paid, activities, nursery, higher, internet, romantic,
freetime, goout, health, absences, G3


Label: alcohol_consumption (Average of Dalc and Walc)

In [2]:
# Imports
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import torch.optim as optim
import torch.nn as nn
import numpy as np
import torch
import csv
import math
import pandas as pd

In [3]:
pd.set_option('display.max_columns', None)

In [4]:
# Importing datasets using csv files
student_math = pd.read_csv('student-mat.csv', sep=';')
student_port = pd.read_csv('student-por.csv', sep=';')

In [5]:
student_math.head(5)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian,traveltime,studytime,failures,schoolsup,famsup,paid,activities,nursery,higher,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,course,mother,2,2,0,yes,no,no,no,yes,yes,no,no,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,course,father,1,2,0,no,yes,no,no,no,yes,yes,no,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,other,mother,1,2,3,yes,no,yes,no,yes,yes,yes,no,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,home,mother,1,3,0,no,yes,yes,yes,yes,yes,yes,yes,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,home,father,1,2,0,no,yes,yes,no,yes,yes,no,no,4,3,2,1,2,5,4,6,10,10

In [6]:
student_port.head(5)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian,traveltime,studytime,failures,schoolsup,famsup,paid,activities,nursery,higher,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,course,mother,2,2,0,yes,no,no,no,yes,yes,no,no,4,3,4,1,1,3,4,0,11,11
1,GP,F,17,U,GT3,T,1,1,at_home,other,course,father,1,2,0,no,yes,no,no,no,yes,yes,no,5,3,3,1,1,3,2,9,11,11
2,GP,F,15,U,LE3,T,1,1,at_home,other,other,mother,1,2,0,yes,no,no,no,yes,yes,yes,no,4,3,2,2,3,3,6,12,13,12
3,GP,F,15,U,GT3,T,4,2,health,services,home,mother,1,3,0,no,yes,no,yes,yes,yes,yes,yes,3,2,2,1,1,5,0,14,14,14
4,GP,F,16,U,GT3,T,3,3,other,other,home,father,1,2,0,no,yes,no,no,yes,yes,no,no,4,3,2,1,2,5,0,11,13,13

In [7]:
# To check both datasets for zero values
print("Math Dataset Zeros")
print((student_math == 0).sum())

print("\nPortuguese Dataset Zeros")
print((student_port == 0).sum())

Math Dataset Zeros
school          0
sex             0
age             0
address         0
famsize         0
Pstatus         0
Medu            3
Fedu            2
Mjob            0
Fjob            0
reason          0
guardian        0
traveltime      0
studytime       0
failures      312
schoolsup       0
famsup          0
paid            0
activities      0
nursery         0
higher          0
internet        0
romantic        0
famrel          0
freetime        0
goout           0
Dalc            0
Walc            0
health          0
absences      115
G1              0
G2             13
G3             38
dtype: int64

Portuguese Dataset Zeros
school          0
sex             0
age             0
address         0
famsize         0
Pstatus         0
Medu            6
Fedu            7
Mjob            0
Fjob            0
reason          0
guardian        0
traveltime      0
studytime       0
failures      549
schoolsup       0
famsup          0
paid            0
activities      0
nursery         0
higher          0
internet        0
romantic        0
famrel          0
freetime        0
goout           0
Dalc            0
Walc            0
health          0
absences      244
G1              1
G2              7
G3             15
dtype: int64

In [8]:
# To check both datasets for missing values 
print("Math Dataset Missing Values")
print(student_math.isnull().sum())

print("\nPortuguese Dataset Missing Values")
print(student_port.isnull().sum())

Math Dataset Missing Values
school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
G1            0
G2            0
G3            0
dtype: int64

Portuguese Dataset Missing Values
school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
G1            0
G2            0
G3            0
dtype: int64

In [9]:
print(student_math.columns.tolist())
print(student_port.columns.tolist())

['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu', 'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime', 'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery', 'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc', 'Walc', 'health', 'absences', 'G1', 'G2', 'G3']
['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu', 'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime', 'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery', 'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc', 'Walc', 'health', 'absences', 'G1', 'G2', 'G3']

In [10]:
print("Math rows:", len(student_math))
print("Portuguese rows:", len(student_port))

Math rows: 395
Portuguese rows: 649

In [11]:
math_df = student_math.drop(columns=['failures', 'absences','G1', 'G2', 'G3'])
port_df = student_port.drop(columns=['failures', 'absences', 'G1', 'G2', 'G3'])

In [12]:
math_df.iloc[200:205]

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian,traveltime,studytime,schoolsup,famsup,paid,activities,nursery,higher,internet,romantic,famrel,freetime,goout,Dalc,Walc,health
200,GP,F,16,U,GT3,T,4,3,health,other,home,mother,1,2,no,yes,no,yes,yes,yes,yes,no,4,3,5,1,5,2
201,GP,F,16,U,GT3,T,2,3,other,other,reputation,mother,1,2,yes,yes,yes,yes,yes,yes,no,no,4,4,3,1,3,4
202,GP,F,17,U,GT3,T,1,1,other,other,course,mother,1,2,no,yes,yes,no,no,yes,no,no,4,4,4,1,3,1
203,GP,F,17,R,GT3,T,2,2,other,other,reputation,mother,1,1,no,yes,no,no,yes,yes,yes,no,5,3,2,1,2,3
204,GP,F,16,R,GT3,T,2,2,services,services,reputation,mother,2,4,no,yes,yes,yes,no,yes,yes,no,5,3,5,1,1,5

In [13]:
port_df.iloc[200:205]

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian,traveltime,studytime,schoolsup,famsup,paid,activities,nursery,higher,internet,romantic,famrel,freetime,goout,Dalc,Walc,health
200,GP,M,16,U,GT3,T,1,2,services,services,other,mother,1,1,no,yes,no,yes,yes,yes,yes,yes,3,3,3,1,2,3
201,GP,M,16,U,LE3,T,2,1,other,other,course,mother,1,2,no,no,no,yes,yes,yes,yes,yes,4,2,3,1,2,5
202,GP,F,17,U,GT3,A,3,3,health,other,reputation,mother,1,2,no,yes,no,no,no,yes,yes,yes,3,3,3,1,3,3
203,GP,M,17,R,GT3,T,1,2,at_home,other,home,mother,1,2,no,no,no,no,yes,yes,no,no,3,1,3,1,5,3
204,GP,F,16,U,GT3,T,2,3,services,services,course,mother,1,2,no,no,no,no,yes,yes,yes,no,4,3,3,1,1,2

In [14]:
diff_df = pd.merge(port_df, math_df, how='left', indicator=True)
port_only = diff_df[diff_df['_merge'] == 'left_only']
print("Rows in Portuguese but not in Math:", len(port_only))

Rows in Portuguese but not in Math: 448

In [18]:
# check duplicates in datasets
print(math_df.duplicated().sum())
print(port_df.duplicated().sum())

0
2

In [ ]:
# show duplicates in port_df
duplicates = port_df[port_df.duplicated()]
print(duplicates)

    school sex  age address famsize Pstatus  Medu  Fedu    Mjob      Fjob  \
442     MS   M   15       R     LE3       T     4     1  health  services
443     MS   M   15       R     LE3       T     4     1  health  services
453     MS   F   16       U     GT3       T     1     2   other  services
454     MS   F   16       U     GT3       T     1     2   other  services

         reason guardian  traveltime  studytime schoolsup famsup paid  \
442  reputation   father           1          2        no    yes   no
443  reputation   father           1          2        no    yes   no
453      course   mother           1          3        no    yes   no
454      course   mother           1          3        no    yes   no

    activities nursery higher internet romantic  famrel  freetime  goout  \
442        yes     yes    yes      yes       no       5         3      4
443        yes     yes    yes      yes       no       5         3      4
453         no     yes    yes       no       no       1         3      2
454         no     yes    yes       no       no       1         3      2

     Dalc  Walc  health
442     1     2       2
443     1     2       2
453     1     2       4
454     1     2       4

In [21]:
# drop duplicates in port_df
port_df = port_df.drop_duplicates()
print(port_df.duplicated().sum())

0

In [14]:
#student_math[['traveltime', 'studytime', 'failures']].head(10)

In [15]:
#student_port[['traveltime', 'studytime', 'failures']].head(10)

In [ ]:
# Rename G3 and remove G1 and G2 for both datasets
#math_df = student_math.drop(columns=['G1', 'G2']).rename(columns={'G3': 'mathgrade'})
#port_df = student_port.drop(columns=['G1', 'G2']).rename(columns={'G3': 'portgrade'})